/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include <stdlib.h>
#include <stdint.h>

typedef void (*InjectVPNPacketFn)(void* data, int len);
typedef void (*MatchFoundCallbackFn)(char* matchID, char* hostID, char* rosterList);
typedef void (*MatchEndedCallbackFn)(char* matchID);

static InjectVPNPacketFn ptrInjectVPNPacket = NULL;

static void SetInjectPacketPointer(InjectVPNPacketFn ptr) {
    ptrInjectVPNPacket = ptr;
}

static void CallInjectVPNPacket(void* data, int len) {
    if (ptrInjectVPNPacket != NULL) {
        ptrInjectVPNPacket(data, len);
    }
}

extern void HandleOutboundPacket(void* data, int len);

static void* GetGoCallback() {
    return (void*)HandleOutboundPacket;
}

static MatchFoundCallbackFn ptrMatchFoundCallback = NULL;
static MatchEndedCallbackFn ptrMatchEndedCallback = NULL;

static void SetMatchFoundCallback(MatchFoundCallbackFn ptr) {
    ptrMatchFoundCallback = ptr;
}

static void CallMatchFound(char* matchID, char* hostID, char* rosterList) {
    if (ptrMatchFoundCallback != NULL) {
        ptrMatchFoundCallback(matchID, hostID, rosterList);
    }
}

static void SetMatchEndedCallback(MatchEndedCallbackFn ptr) {
    ptrMatchEndedCallback = ptr;
}

static void CallMatchEnded(char* matchID) {
    if (ptrMatchEndedCallback != NULL) {
        ptrMatchEndedCallback(matchID);
    }
}

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern char* UpdateMyProfile(char* username, char* avatarURL);
extern char* GetPeerProfile(char* peerID);
extern char* GenerateAndRegisterFriendCode(void);
extern char* AddFriendByCode(char* code);
extern char* FetchFriendList(void);
extern char* GetNetworkMatches(void);
extern char* StartEdenNode(char* virtualIP, char* gameID);
extern char* StartMatch(char* matchID, char* playerList, char* password);
extern char* GetMatchPassword(char* matchID);
extern void StopEdenNode(void);
extern char* AbortMatch(char* matchID);
extern char* SubmitGameBlock(int duration, int playerCount);
extern char* GetWalletPubKey(void);
extern double GetWalletBalance(char* address);
extern char* PlaceBet(char* matchID, char* team, double amount);
extern int SendTransaction(char* receiver, double amount);
extern void InitPacketBridge(InjectVPNPacketFn fn);
extern void HandleOutboundPacket(void* data, int length);
extern void RegisterMatchCallback(MatchFoundCallbackFn fn);
extern void LeaveMatchmaking(void);
extern void BroadcastMatchReady(char* matchID);
extern char* GetMatchReadyStates(char* matchID);
extern char* GetMatchRoster(char* matchID);
extern char* GetMyPeerID(void);
extern char* RespondToFriendRequest(char* peerID, int accept);
extern void AdvertiseHostLobby(char* mode, char* mapName);
extern char* SubmitDodgePenalty(char* matchID, char* dodgerPeerID);
extern char* GetValidatorMetrics(char* peerID);
extern char* AutoConnectToPeers(char* targetMode, char* targetMap);
extern void ConnectToPeer(char* peerID);
extern char* EnterMatchmaking(char* mode, char* partyList, int expectedPlayers);
extern void BroadcastMapVeto(char* matchID, char* mapName);
extern char* GetMatchVetoes(char* matchID);
extern void RegisterMatchEndedCallback(MatchEndedCallbackFn fn);
extern char* GetMyBanExpiry(void);
extern int IsPeerAlive(void);
extern char* GetIPForPeer(char* peerIDStr);
extern void FreeString(char* str);

#ifdef __cplusplus
}
#endif
